language: objective-c
install:
  - npm install -g cordova
  - npm install -g ios-sim
  - npm install -g ios-deploy
  - npm install -g cordova-paramedic
  - npm install
script:
  - npm test
  - cordova create testapp us.eidinger.testapp
  - cd testapp
  - cordova platform add ios
  - cordova plugin install /Users/travis/build/MarcoEidinger/cordova-disable-copy-paste
  - cordova build
